"""sheet sync tables and astrologer expert_id

Revision ID: 99b9c51c28c0
Revises: f4ec7928b138
Create Date: 2026-08-13 02:18:15.471104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b9c51c28c0'
down_revision: Union[str, None] = 'f4ec7928b138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_astrologer_roster',
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('expert_id')
    )
    op.create_table('sheet_kyc_records',
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('expert_name', sa.String(length=120), nullable=True),
    sa.Column('kyc_status', sa.String(length=40), nullable=True),
    sa.Column('verification_status', sa.String(length=40), nullable=True),
    sa.Column('entry_status', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('expert_id')
    )
    op.create_table('sheet_payout_status',
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('wallet_balance', sa.BigInteger(), nullable=True),
    sa.Column('payout', sa.BigInteger(), nullable=True),
    sa.Column('incentive', sa.BigInteger(), nullable=True),
    sa.Column('penalty_amount', sa.BigInteger(), nullable=True),
    sa.Column('total_after_tax', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('processed_at', sa.String(length=60), nullable=True),
    sa.Column('cycle_tab', sa.String(length=60), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('expert_id')
    )
    op.create_table('sheet_queue_performance',
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('expert_name', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(length=120), nullable=True),
    sa.Column('users_connected', sa.Integer(), nullable=True),
    sa.Column('queues_connected', sa.Integer(), nullable=True),
    sa.Column('total_talktime_min', sa.Integer(), nullable=True),
    sa.Column('sheet_updated_at', sa.String(length=60), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('expert_id')
    )
    op.create_table('sheet_wallet_balance',
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('eligible', sa.BigInteger(), nullable=True),
    sa.Column('sheet_updated_at', sa.String(length=60), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('expert_id')
    )
    op.add_column('astrologers', sa.Column('expert_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_astrologers_expert_id'), 'astrologers', ['expert_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_astrologers_expert_id'), table_name='astrologers')
    op.drop_column('astrologers', 'expert_id')
    op.drop_table('sheet_wallet_balance')
    op.drop_table('sheet_queue_performance')
    op.drop_table('sheet_payout_status')
    op.drop_table('sheet_kyc_records')
    op.drop_table('sheet_astrologer_roster')
    # ### end Alembic commands ###
