"""add calls table

Revision ID: c42af52a06dd
Revises: f8a9b1c2d3e4
Create Date: 2026-09-03 13:15:50.470666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42af52a06dd'
down_revision: Union[str, None] = 'f8a9b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('astrologer_id', sa.Integer(), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RINGING', 'IN_PROGRESS', 'ENDED', 'FAILED', name='call_status', native_enum=False), nullable=False),
    sa.Column('ended_reason', sa.String(length=80), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['astrologer_id'], ['astrologers.id'], ),
    sa.ForeignKeyConstraint(['created_ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_astrologer_id'), 'calls', ['astrologer_id'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=True)
    # NOTE: autogenerate also proposed an admins.role type change here
    # (VARCHAR -> the same Enum it already logically is) — a known
    # false-positive on native_enum=False columns, unrelated to this
    # migration's actual purpose, so it's deliberately omitted.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_astrologer_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
