"""analytics, feedback, ticket satisfaction, admin signup

Revision ID: f4ec7928b138
Revises: 011c5105eaab
Create Date: 2026-08-11 16:13:19.164918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ec7928b138'
down_revision: Union[str, None] = '011c5105eaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('astrologer_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('sub_category', sa.String(length=80), nullable=True),
    sa.Column('resolved_by', sa.Enum('BOT', 'ESCALATED', name='session_resolution', native_enum=False), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['astrologer_id'], ['astrologers.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_astrologer_id'), 'chat_sessions', ['astrologer_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.alter_column('admins', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('satisfaction', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'satisfaction')
    op.drop_column('tickets', 'resolved_at')
    op.alter_column('admins', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_astrologer_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('email_log')
    # ### end Alembic commands ###
