"""add role to admins

Revision ID: f7ea76fd8032
Revises: 99b9c51c28c0
Create Date: 2026-08-13 16:20:25.310501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ea76fd8032'
down_revision: Union[str, None] = '99b9c51c28c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'admins',
        sa.Column(
            'role',
            sa.Enum('KAM', 'CS', name='admin_role', native_enum=False),
            nullable=False,
            server_default='KAM',
        ),
    )
    op.alter_column('admins', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'role')
    # ### end Alembic commands ###
